# Generated by Django 4.1.7 on 2023-03-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_keyword_comment_is_active_image_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keyword',
            field=models.ManyToManyField(blank=True, related_name='categories_keyword', to='products.keyword'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keyword',
            field=models.ManyToManyField(blank=True, related_name='products_keyword', to='products.keyword'),
        ),
    ]
