# Generated by Django 4.1.7 on 2023-02-21 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('partnerName', models.CharField(blank=True, max_length=30, null=True)),
                ('partnerId', models.CharField(blank=True, max_length=11, null=True)),
                ('phoneUser', models.CharField(blank=True, max_length=11, null=True)),
                ('comment', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_status', models.IntegerField(choices=[(0, 'Failed'), (1, 'Success')], default=1)),
                ('payment_type', models.IntegerField(choices=[(0, 'pay'), (1, 'refund')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_order', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
